### ISSUE TITLE
NodeJs 14 x runtime required for LambdaLayer

### ISSUE THREAD

**Issue by agarwala95** [aws-samples/aws-alien-attack#11]
The error is with CDK deployment of Lambda:
Resource handler returned message: "The runtime parameter of nodejs10.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs14.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 6e09214d-1abc-4f66-8fc3-2f3ab42cb739, Extended Request ID: null)" (RequestToken: 44f58a32-76ce-1dab-4621-8d8e01eeb35d, HandlerErrorCode: InvalidRequest)

**Comment by williams-katie** [comment]
Fix has been applied. Pushed new change to lambda layers and updated runtimes to NodeJS 14. Please try cloning the repository and building a new environment with this new code so that you can deploy  the Lambda Functions with updated NodeJS version.
